## Extracting elative construction instances from Estonian Reference Corpus

 - Extracting elative construction pattern matches from pre-filtered Estonian Reference Corpus sentences.
 - Semantically filtering construction members in elative case and allocating found pattern matches to categories of material and occupation/nationality/role.
 - Finding 10 most common and most attracted construction member lemmas in elative case for both categories.
 - Finding 5 most common elative construction phrases per each lemma for both categories.
 - Finding 3 example sentences per each phrase for both categories.
 - Saving results in CSV-format.

Later, these results will be exported to EKILEX database.

In [ ]:
%load_ext autoreload
%autoreload 2

In [ ]:
import sys

sys.path.append("..")

import csv

from methods.data_extraction.pattern_matching import *
from methods.data_extraction.helper_methods import *
from methods.data_extraction.conx_statistics import *
from methods.data_extraction.example_extraction import *

### I Reading pre-filtered Estonian Reference Corpus sentences

In [ ]:
INPUT_DIR = "../input_data/koondkorpus_sentences/el_conx_sentences_cleaned/"

In [81]:
data = read_texts_from_json(INPUT_DIR)

In [ ]:
# EstNLTK Text-object of a sentence and it's annotation layers
data[0]

Text(text='Mis selle pronksist kujuga ikka juhtuda sai . . . ”')

In [ ]:
# stanza syntax layer
data[0].v172_stanza_syntax

Layer(name='v172_stanza_syntax', attributes=('id', 'lemma', 'upostag', 'xpostag', 'feats', 'head', 'deprel', 'deps', 'misc', 'parent_span', 'children'), spans=SL[Span('Mis', [{'id': 1, 'lemma': 'mis', 'upostag': 'P', 'xpostag': 'P', 'feats': {'sg': 'sg', 'nom': 'nom'}, 'head': 6, 'deprel': 'nsubj', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('selle', [{'id': 2, 'lemma': 'see', 'upostag': 'P', 'xpostag': 'P', 'feats': {'sg': 'sg', 'gen': 'gen'}, 'head': 3, 'deprel': 'det', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('pronksist', [{'id': 3, 'lemma': 'pronks', 'upostag': 'S', 'xpostag': 'S', 'feats': {'el': 'el', 'sg': 'sg', 'com': 'com'}, 'head': 4, 'deprel': 'nmod', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('kujuga', [{'id': 4, 'lemma': 'kuju', 'upostag': 'S', 'xpostag': 'S', 'feats': {'sg': 'sg', 'com': 'com', 'kom': 'kom'}, 'head': 6, 'deprel': 'obl', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('ikka', [{'id': 5, 'lemma': 'ikka', 'upostag': 'D', 'xpostag': 'D', 'feats': {}, 'head': 6, 'deprel': 'advmod', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('juhtuda', [{'id': 6, 'lemma': 'juhtuma', 'upostag': 'V', 'xpostag': 'V', 'feats': {'inf': 'inf', 'mod': 'mod'}, 'head': 0, 'deprel': 'root', 'deps': '_', 'misc': '_', 'parent_span': None, 'children': <class 'tuple'>}]),
Span('sai', [{'id': 7, 'lemma': 'saama', 'upostag': 'V', 'xpostag': 'V', 'feats': {'af': 'af', 'ps': 'ps', 'sg': 'sg', 'ps3': 'ps3', 'impf': 'impf', 'main': 'main', 'indic': 'indic'}, 'head': 6, 'deprel': 'aux', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('.', [{'id': 8, 'lemma': '.', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 6, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('.', [{'id': 9, 'lemma': '.', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 6, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('.', [{'id': 10, 'lemma': '.', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 6, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('”', [{'id': 11, 'lemma': '”', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 6, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}])])

In [ ]:
# morphological analysis layer
data[0].morph_analysis

Layer(name='morph_analysis', attributes=('normalized_text', 'lemma', 'root', 'root_tokens', 'ending', 'clitic', 'form', 'partofspeech'), spans=SL[Span('Mis', [{'normalized_text': 'Mis', 'lemma': 'mis', 'root': 'mis', 'root_tokens': ['mis'], 'ending': '0', 'clitic': '', 'form': 'sg n', 'partofspeech': 'P'}, {'normalized_text': 'Mis', 'lemma': 'mis', 'root': 'mis', 'root_tokens': ['mis'], 'ending': '0', 'clitic': '', 'form': 'pl n', 'partofspeech': 'P'}]),
Span('selle', [{'normalized_text': 'selle', 'lemma': 'see', 'root': 'see', 'root_tokens': ['see'], 'ending': '0', 'clitic': '', 'form': 'sg g', 'partofspeech': 'P'}]),
Span('pronksist', [{'normalized_text': 'pronksist', 'lemma': 'pronks', 'root': 'pronks', 'root_tokens': ['pronks'], 'ending': 'st', 'clitic': '', 'form': 'sg el', 'partofspeech': 'S'}]),
Span('kujuga', [{'normalized_text': 'kujuga', 'lemma': 'kuju', 'root': 'kuju', 'root_tokens': ['kuju'], 'ending': 'ga', 'clitic': '', 'form': 'sg kom', 'partofspeech': 'S'}]),
Span('ikka', [{'normalized_text': 'ikka', 'lemma': 'ikka', 'root': 'ikka', 'root_tokens': ['ikka'], 'ending': '0', 'clitic': '', 'form': '', 'partofspeech': 'D'}]),
Span('juhtuda', [{'normalized_text': 'juhtuda', 'lemma': 'juhtuma', 'root': 'juhtu', 'root_tokens': ['juhtu'], 'ending': 'da', 'clitic': '', 'form': 'da', 'partofspeech': 'V'}]),
Span('sai', [{'normalized_text': 'sai', 'lemma': 'saama', 'root': 'saa', 'root_tokens': ['saa'], 'ending': 'i', 'clitic': '', 'form': 's', 'partofspeech': 'V'}]),
Span('.', [{'normalized_text': '.', 'lemma': '.', 'root': '.', 'root_tokens': ['.'], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}]),
Span('.', [{'normalized_text': '.', 'lemma': '.', 'root': '.', 'root_tokens': ['.'], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}]),
Span('.', [{'normalized_text': '.', 'lemma': '.', 'root': '.', 'root_tokens': ['.'], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}]),
Span('”', [{'normalized_text': '”', 'lemma': '”', 'root': '”', 'root_tokens': ['”'], 'ending': '', 'clitic': '', 'form': '', 'partofspeech': 'Z'}])])

### II Extracting elative construction pattern matches

In [ ]:
# setting up pattern of elative construction
el_conx_pattern = {
        "nodes": {
            "A": {
                "deprels": ["nmod"], # A has to be a substantive and a nominal modifier in singular elative case
                "partofspeeches": ["S"],
                "forms": ["sg el"],
                "lemmas": None,
                "lemma_regex": None,
                "instances": None
                },
            "B": {
                "deprels": None,
                "partofspeeches": ["S"], # B has to be a substantive
                "forms": None,
                "lemmas": None,
                "lemma_regex": None,
                "instances": None
                }
        },
        "node_restrictions": {
            "A": None,
            "B": {"deprels": ["nmod"], # B can't be a nominal modifier, in terminative case, nor can it's lemma end with "mine"-clitic
                  "partofspeeches": None,
                  "forms": ["sg ter", "pl ter"],
                  "lemmas": None,
                  "lemma_regex": [r".*mine$"],
                  "instances": None,
                  "parent": None,
                  "child": None
                }
        },
        "edges": [
            ("B", "A")  # B is head of A
        ],
        "order": [
            ("A", "BEFORE", "B") # A has to appear before B in text
        ]
    }

In [ ]:
# finding elative construction instances from Estonian Reference Corpus sentences based on pattern
match_sentences = []
matches = []

for idx, sentence in enumerate(data):

    sent_matches = get_pattern(stanza_words = sentence.v172_stanza_syntax, 
                                pattern = el_conx_pattern, 
                                anchor_name = "B")
    if len(sent_matches) > 0:
        match_sentences.append(sentence.v172_stanza_syntax)
        matches.append(sent_matches)

In [ ]:
# example result printout
print(match_sentences[0])
print()
print(matches[0])

Layer(name='v172_stanza_syntax', attributes=('id', 'lemma', 'upostag', 'xpostag', 'feats', 'head', 'deprel', 'deps', 'misc', 'parent_span', 'children'), spans=SL[Span('Mis', [{'id': 1, 'lemma': 'mis', 'upostag': 'P', 'xpostag': 'P', 'feats': {'sg': 'sg', 'nom': 'nom'}, 'head': 6, 'deprel': 'nsubj', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('selle', [{'id': 2, 'lemma': 'see', 'upostag': 'P', 'xpostag': 'P', 'feats': {'sg': 'sg', 'gen': 'gen'}, 'head': 3, 'deprel': 'det', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('pronksist', [{'id': 3, 'lemma': 'pronks', 'upostag': 'S', 'xpostag': 'S', 'feats': {'el': 'el', 'sg': 'sg', 'com': 'com'}, 'head': 4, 'deprel': 'nmod', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('kujuga', [{'id': 4, 'lemma': 'kuju', 'upostag': 'S', 'xpostag': 'S', 'feats': {'sg': 'sg', 'com': 'com', 'kom': 'kom'}, 'head': 6, 'deprel': 'obl', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]),
Span('ikka', [{'id': 5, 'lemma': 'ikka', 'upostag': 'D', 'xpostag': 'D', 'feats': {}, 'head': 6, 'deprel': 'advmod', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('juhtuda', [{'id': 6, 'lemma': 'juhtuma', 'upostag': 'V', 'xpostag': 'V', 'feats': {'inf': 'inf', 'mod': 'mod'}, 'head': 0, 'deprel': 'root', 'deps': '_', 'misc': '_', 'parent_span': None, 'children': <class 'tuple'>}]),
Span('sai', [{'id': 7, 'lemma': 'saama', 'upostag': 'V', 'xpostag': 'V', 'feats': {'af': 'af', 'ps': 'ps', 'sg': 'sg', 'ps3': 'ps3', 'impf': 'impf', 'main': 'main', 'indic': 'indic'}, 'head': 6, 'deprel': 'aux', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('.', [{'id': 8, 'lemma': '.', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 6, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('.', [{'id': 9, 'lemma': '.', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 6, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('.', [{'id': 10, 'lemma': '.', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 6, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}]),
Span('”', [{'id': 11, 'lemma': '”', 'upostag': 'Z', 'xpostag': 'Z', 'feats': {}, 'head': 6, 'deprel': 'punct', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': ()}])])

[{'B': Span('kujuga', [{'id': 4, 'lemma': 'kuju', 'upostag': 'S', 'xpostag': 'S', 'feats': {'sg': 'sg', 'com': 'com', 'kom': 'kom'}, 'head': 6, 'deprel': 'obl', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}]), 'A': Span('pronksist', [{'id': 3, 'lemma': 'pronks', 'upostag': 'S', 'xpostag': 'S', 'feats': {'el': 'el', 'sg': 'sg', 'com': 'com'}, 'head': 4, 'deprel': 'nmod', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}])}]

In [113]:
# number of sentences in which elative construction occurs
print(len(match_sentences))

89605

In [ ]:
# total number of elative construction matches found
n_matches = 0

for sent_matches_list in matches:
    n_matches+=len(sent_matches_list)

print(n_matches)

91784

In [ ]:
# number of sentences in which elative construction occurs more than once
n_multiple_matches = 0

for sent_matches_list in matches:
    if len(sent_matches_list) > 1:
        n_multiple_matches+=1

print(n_multiple_matches)

2017

In [86]:
# first 5 examples of sentence, elative construction phrase match and syntactic head of the phrase
for i in range(len(match_sentences)):
    if i == 5:
        break
    display_example(i, match_sentences, matches)

Mis selle pronksist kujuga ikka juhtuda sai . . . ”
pronksist kujuga
kujuga

Mori nimetatud uues valitsuses jääb endiselt rahandusministri ametisse 81-aastane ekspeaminister Kiichi Miyazawa ning veteranist välisminister Yohei Kono .
veteranist välisminister
välisminister

Priit Press , floristist ettevõtja Aegajalt tunnen puudust , sest üleliia ei ole raha kunagi , kuid ma ei tee sellest probleemi .
floristist ettevõtja
ettevõtja

Oleme tuttavad lasteaiast saadik , viimased 10 aastat oleme koos olnud .
lasteaiast saadik
saadik

Vastassoost partneri valikul otsitakse tavaliselt vastavale soorollile tüüpilise käitumise väljendamist .
Vastassoost partneri
partneri

### III Preparing lemmas and form codes of members in elative case from extracted pattern matches for semantic filtering and computing statistics

In [87]:
# list of syntactic heads of construction examples
conx_heads_list = [[get_conx_head(sent, match) for idx2, match in enumerate(matches[idx1])] for idx1, sent in enumerate(match_sentences)]
print(conx_heads_list[0])

# list of specified members of construction examples
conx_member_list = [[get_conx_member(match, "A") for idx2, match in enumerate(matches[idx1])] for idx1, sent in enumerate(match_sentences)]
print(conx_member_list[0])

# list of specified members of construction examples as lemmas
conx_member_lemma_list = [[member.morph_analysis.lemma[0] for member in members] for idx1, members in enumerate(conx_member_list)]
print(conx_member_lemma_list[0])

# flattened version of member lemma list
lemma_list = [member for members in conx_member_lemma_list for member in members]
print(lemma_list[0])

# list of specified members of construction examples as form codes
conx_member_form_codes_list = [[get_form_code(member) for member in members] for idx1, members in enumerate(conx_member_list)]
print(conx_member_form_codes_list[0])

# flattened version of member form codes list
form_codes = [member for members in conx_member_form_codes_list for member in members]
print(form_codes[0])

[Span('kujuga', [{'id': 4, 'lemma': 'kuju', 'upostag': 'S', 'xpostag': 'S', 'feats': {'sg': 'sg', 'com': 'com', 'kom': 'kom'}, 'head': 6, 'deprel': 'obl', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}])]
[Span('pronksist', [{'id': 3, 'lemma': 'pronks', 'upostag': 'S', 'xpostag': 'S', 'feats': {'el': 'el', 'sg': 'sg', 'com': 'com'}, 'head': 4, 'deprel': 'nmod', 'deps': '_', 'misc': '_', 'parent_span': <class 'estnltk_core.layer.span.Span'>, 'children': <class 'tuple'>}])]
['pronks']
pronks
['pronks_SgEl_S']
pronks_SgEl_S

In [88]:
lemma_list[:10]

['pronks',
 'veteran',
 'florist',
 'lasteaed',
 'vastassugu',
 'rahvamass',
 'klaas',
 'pealinn',
 'puit',
 'muinsuskaitsja']

### IV Semantic filtering: material vs occupation/nationality/role

In [ ]:
# Importing lists of material and occupation/nationality/role lemmas
SEM_DATA_PATH = "../../../../../002_semantic_annotation/results/reference_corpus_data/elative_all/"
FILENAME1 = "material.txt"
FILENAME2 = "occupation_nationality_role.txt"

material: list[str] = read_txt_to_list(f"{SEM_DATA_PATH}{FILENAME1}")
occupation_nationality_role: list[str] = read_txt_to_list(f"{SEM_DATA_PATH}{FILENAME2}")

In [90]:
print(material[:5])
print(occupation_nationality_role[:5])

['liha', 'luu', 'puu', 'põlevkivi', 'eebenipuu']
['isik', 'treener', 'demokraat', 'vabariiklane', 'keskerakondlane']

In [91]:
# Filtering and categorizing pattern match lemmas
elative_material: list[str] = get_filtered_list(lemma_list, material)
elative_attribute: list[str] = get_filtered_list(lemma_list, occupation_nationality_role)

In [92]:
elative_material[:10]

['pronks',
 'klaas',
 'puit',
 'tekstiil',
 'metall',
 'pronks',
 'liivakivi',
 'metall',
 'plastik',
 'leib']

In [93]:
elative_attribute[:10]

['veteran',
 'taanlane',
 'majandusteadlane',
 'võitja',
 'norralane',
 'ameeriklane',
 'ameeriklane',
 'venelane',
 'iisraellane',
 'ameeriklane']

### V Elative material

In [94]:
# list of construction members in elative case as EKILEX form codes
el_material_conx_member_form_codes_list = [[get_form_code(member) for member in members if member.morph_analysis.lemma[0] in elative_material] for idx1, members in enumerate(conx_member_list)]
el_material_conx_member_form_codes_list_cleaned = [el for el in el_material_conx_member_form_codes_list if len(el) > 0]
print(el_material_conx_member_form_codes_list_cleaned[0])

# flattened version of member form codes list
el_material_form_codes = [member for members in el_material_conx_member_form_codes_list_cleaned for member in members]
print(el_material_form_codes[0])

['pronks_SgEl_S']
pronks_SgEl_S

In [95]:
# calculating statistics, getting n most frequent and n most attracted form code lemmas
# n most common ja n most attracted frequency- ja LL-scores
el_material_most_common, el_material_most_attracted = get_statistics(all_member_forms=el_material_form_codes, 
                                                      conx_freq=len(el_material_form_codes),
                                                      n_most_common=10,
                                                      n_most_attracted=10)

In [96]:
print(el_material_most_common)
print(el_material_most_attracted)

{}
{'metall': [1153, 9063.242], 'klaas': [874, 6464.116], 'puit': [777, 5660.311], 'puu': [823, 5516.514], 'kivi': [410, 2883.572], 'plastmass': [389, 2845.022], 'materjal': [386, 2421.024], 'nahk': [330, 2251.421], 'teras': [307, 2194.799], 'pronks': [293, 2173.515]}

In [97]:
# extracting examples for n most frequent and n most attracted lemmas
material_top10 = el_material_most_common | el_material_most_attracted

material_n_most_common_phrases = dict()
material_n_most_common_phrases_stanza = dict()

for lemma in material_top10.keys():
    phrase_examples_str, phrase_exaples_stanza = extract_n_most_common_phrases(lemma, 5, "A", match_sentences, matches)
    material_n_most_common_phrases[lemma] = phrase_examples_str
    material_n_most_common_phrases_stanza[lemma] = phrase_exaples_stanza

material_phrase_example_sentences = dict()

for example_list in material_n_most_common_phrases.values():
    for example in example_list:
        phrase_sentences = extract_example_sentences(example, 3, match_sentences, matches)
        material_phrase_example_sentences[example] = phrase_sentences

In [98]:
material_n_most_common_phrases

{'metall': ['metallist ese',
  'metallist karkass',
  'metallist kett',
  'metallist toru',
  'metallist keerdtrepp'],
 'klaas': ['klaasist sein',
  'klaasist pudel',
  'klaasist vahesein',
  'klaasist uks',
  'klaasist ese'],
 'puit': ['puidust elumaja',
  'puidust hoone',
  'puidust osa',
  'puidust laud',
  'puidust maja'],
 'puu': ['puust linn',
  'puust rist',
  'puust elumaja',
  'puust mees',
  'puust laud'],
 'kivi': ['Kivist külaline',
  'kivist hoone',
  'kivist ehitis',
  'kivist tööriist',
  'kivist sein'],
 'plastmass': ['plastmassist pea',
  'plastmassist pudel',
  'plastmassist asi',
  'plastmassist kast',
  'plastmassist mänguasi'],
 'materjal': ['materjalist sisetald',
  'materjalist püks',
  'materjalist kott',
  'materjalist toode',
  'materjalist sokk'],
 'nahk': ['nahast king',
  'nahast tugitool',
  'nahast jalats',
  'nahast saabas',
  'nahast rihm'],
 'teras': ['terasest närv',
  'terasest lehtvaltstoode',
  'terasest pann',
  'terasest pott',
  'terasest nuga'],
 'pronks': ['pronksist kuju',
  'pronksist koopia',
  'pronksist autasu',
  'pronksist skulptuur',
  'pronksist bareljeef']}

Saving results in CSV-format:

In [ ]:
# elative material construction
top10_material = el_material_most_attracted | el_material_most_common

material_data = []

for word, stats in top10_material.items():
    for idx1, phrase in enumerate(material_n_most_common_phrases[word]):
        for idx2, sentence in enumerate(material_phrase_example_sentences[phrase]):
            data_dct = {
                        "lemma": word, 
                        "frequency": stats[0], 
                        "salience": stats[1], 
                        "phrase": phrase, 
                        "sentence": " ".join([word.text for word in sentence])
                        }
            material_data.append(data_dct)

In [101]:
material_data[:10]

[{'lemma': 'metall',
  'frequency': 1153,
  'salience': 9063.242,
  'phrase': 'metallist ese',
  'sentence': 'Peale kaardihoidjate valmistame veel puidust ja metallist esemeid .'},
 {'lemma': 'metall',
  'frequency': 1153,
  'salience': 9063.242,
  'phrase': 'metallist ese',
  'sentence': 'Väga palju on kudumeid , tekke , vaipu , rahvarõivakomplekte , ehteid , nukke ja seinapilte , puust , nahast ja metallist esemeid .'},
 {'lemma': 'metall',
  'frequency': 1153,
  'salience': 9063.242,
  'phrase': 'metallist ese',
  'sentence': 'ETA andmetel märkas Halliku talu peremees põldu kultiveerides metallist eset , mis lähemal uurimisel osutus 82-millimeetrise kaliibriga miiniks .'},
 {'lemma': 'metall',
  'frequency': 1153,
  'salience': 9063.242,
  'phrase': 'metallist karkass',
  'sentence': 'Selle valmistamiseks müüakse metallist karkasse , mis täidetakse turba või kompostmullaga .'},
 {'lemma': 'metall',
  'frequency': 1153,
  'salience': 9063.242,
  'phrase': 'metallist karkass',
  'sentence': 'Jürgen sai bioproteesi , milles puudub võõrkeha , metallist karkass , ning tema pääseb antikoagulandi võtmisest .'},
 {'lemma': 'metall',
  'frequency': 1153,
  'salience': 9063.242,
  'phrase': 'metallist karkass',
  'sentence': 'Siis metallist karkassiga , mille vahel olid küünlad ja inglid .'},
 {'lemma': 'metall',
  'frequency': 1153,
  'salience': 9063.242,
  'phrase': 'metallist kett',
  'sentence': 'Seljas olid tal sinine teksajakk ja pruun džemper , jalas mustad teksased ja pruunid kingad ning kaelas valgest metallist kett väikese ristiga .'},
 {'lemma': 'metall',
  'frequency': 1153,
  'salience': 9063.242,
  'phrase': 'metallist kett',
  'sentence': 'Mehe kaelas oli kollasest metallist kett ristiga ja tema esihammastel olid metallkroonid .'},
 {'lemma': 'metall',
  'frequency': 1153,
  'salience': 9063.242,
  'phrase': 'metallist kett',
  'sentence': 'Parema käe randmel tumedast metallist kett , mille küljes 1 südame - ja 6 elevandikujulist ripatsit .'},
 {'lemma': 'metall',
  'frequency': 1153,
  'salience': 9063.242,
  'phrase': 'metallist toru',
  'sentence': 'Vanas alajaamas tekkis isolaatori purunemise tõttu lühis , metallist toru juhtis voolu lauta'}]

In [ ]:
with open('../../../../results/reference_corpus_data/elative_construction/elative_material_construction.csv', 'w', encoding='utf-8', newline='') as csvfile:
    fieldnames = ['lemma', 'frequency', 'salience', 'phrase', 'sentence']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(material_data)

### VI Elative occupation/nationality/role

In [103]:
# list of specified members of construction examples as form codes
el_attribute_conx_member_form_codes_list = [[get_form_code(member) for member in members if member.morph_analysis.lemma[0] in elative_attribute] for idx1, members in enumerate(conx_member_list)]
el_attribute_conx_member_form_codes_list_cleaned = [el for el in el_attribute_conx_member_form_codes_list if len(el) > 0]
print(el_attribute_conx_member_form_codes_list_cleaned[0])

# flattened version of member form codes list
el_attribute_form_codes = [member for members in el_attribute_conx_member_form_codes_list_cleaned for member in members]
print(el_attribute_form_codes[0])

['veteran_SgEl_S']
veteran_SgEl_S

In [104]:
# calculating statistics, getting n most frequent and n most attracted form code lemmas
# n most common ja n most attracted frequency- ja LL-scores
el_attribute_most_common, el_attribute_most_attracted = get_statistics(all_member_forms=el_attribute_form_codes, 
                                                      conx_freq=len(el_attribute_form_codes),
                                                      n_most_common=10,
                                                      n_most_attracted=10)

In [105]:
print(el_attribute_most_common)
print(el_attribute_most_attracted)

{'demokraat': [399, 2929.957]}
{'isik': [2978, 21565.245], 'eestlane': [1267, 8642.708], 'keskerakondlane': [709, 5226.385], 'ameeriklane': [705, 4803.704], 'reformierakondlane': [640, 4765.2], 'soomlane': [604, 4176.886], 'venelane': [484, 3434.328], 'sakslane': [473, 3353.805], 'vabariiklane': [414, 3070.759], 'hollandlane': [398, 3004.485]}

In [106]:
# extracting examples for n most frequent and n most attracted lemmas
attribute_top10 = el_attribute_most_common | el_attribute_most_attracted

attribute_n_most_common_phrases = dict()
attribute_n_most_common_phrases_stanza = dict()

for lemma in attribute_top10.keys():
    phrase_examples_str, phrase_exaples_stanza = extract_n_most_common_phrases(lemma, 5, "A", match_sentences, matches)
    attribute_n_most_common_phrases[lemma] = phrase_examples_str
    attribute_n_most_common_phrases_stanza[lemma] = phrase_exaples_stanza

attribute_phrase_example_sentences = dict()

for example_list in attribute_n_most_common_phrases.values():
    for example in example_list:
        phrase_sentences = extract_example_sentences(example, 3, match_sentences, matches)
        attribute_phrase_example_sentences[example] = phrase_sentences

In [107]:
attribute_n_most_common_phrases

{'demokraat': ['demokraadist senaator',
  'demokraadist president',
  'demokraadist kuberner',
  'Demokraadist senaator',
  'demokraadist liige'],
 'isik': ['isikust ettevõtja',
  'isikust aktsionär',
  'isikust võlgnik',
  'isikust omanik',
  'isikust esindaja'],
 'eestlane': ['eestlasest narkokuller',
  'eestlasest ärimees',
  'eestlasest linnapea',
  'eestlasest ründaja',
  'eestlasest sõber'],
 'keskerakondlane': ['keskerakondlasest abilinnapea',
  'keskerakondlasest liige',
  'keskerakondlasest esimees',
  'keskerakondlasest linnapea',
  'Keskerakondlasest abilinnapea'],
 'ameeriklane': ['ameeriklasest tagamees',
  'ameeriklasest keskmängija',
  'ameeriklasest mängujuht',
  'ameeriklasest äär',
  'ameeriklasest tsenter'],
 'reformierakondlane': ['reformierakondlasest linnapea',
  'reformierakondlasest esimees',
  'reformierakondlasest abilinnapea',
  'reformierakondlasest liige',
  'Reformierakondlasest abilinnapea'],
 'soomlane': ['soomlasest peatreener',
  'soomlasest omanik',
  'soomlasest liige',
  'soomlasest maailmameister',
  'soomlasest treener'],
 'venelane': ['venelasest keskmängija',
  'venelasest tsenter',
  'venelasest omanik',
  'venelasest äär',
  'venelasest ärimees'],
 'sakslane': ['sakslasest treener',
  'sakslasest peatreener',
  'sakslasest väravavaht',
  'sakslasest piloot',
  'sakslasest sõber'],
 'vabariiklane': ['vabariiklasest senaator',
  'vabariiklasest president',
  'vabariiklasest kuberner',
  'Vabariiklasest senaator',
  'vabariiklasest kongresmen'],
 'hollandlane': ['hollandlasest peatreener',
  'hollandlasest treener',
  'hollandlasest juhendaja',
  'hollandlasest ründaja',
  'hollandlasest kaitsja']}

Saving results in CSV-format:

In [109]:
# elative material construction
top10_attribute = el_attribute_most_attracted | el_attribute_most_common

attribute_data = []

for word, stats in top10_attribute.items():
    for idx1, phrase in enumerate(attribute_n_most_common_phrases[word]):
        for idx2, sentence in enumerate(attribute_phrase_example_sentences[phrase]):
            data_dct = {
                        "lemma": word, 
                        "frequency": stats[0], 
                        "salience": stats[1], 
                        "phrase": phrase, 
                        "sentence": " ".join([word.text for word in sentence])
                        }
            attribute_data.append(data_dct)

In [110]:
attribute_data[:10]

[{'lemma': 'isik',
  'frequency': 2978,
  'salience': 21565.245,
  'phrase': 'isikust ettevõtja',
  'sentence': 'Füüsilisest isikust ettevõtja tuludeklaratsiooni vorm E erineb mõnevõrra eelmise aasta vastavast vormist .'},
 {'lemma': 'isik',
  'frequency': 2978,
  'salience': 21565.245,
  'phrase': 'isikust ettevõtja',
  'sentence': 'Füüsilisest isikust ettevõtja arvestusperiood on kalendriaasta .'},
 {'lemma': 'isik',
  'frequency': 2978,
  'salience': 21565.245,
  'phrase': 'isikust ettevõtja',
  'sentence': 'Eelnõu säilitab ka füüsilisest isikust ettevõtjate tulumaksustamise .'},
 {'lemma': 'isik',
  'frequency': 2978,
  'salience': 21565.245,
  'phrase': 'isikust aktsionär',
  'sentence': 'Füüsilisest isikust aktsionäril palume esitada isikut tõendav dokument , esindajal ka volikiri .'},
 {'lemma': 'isik',
  'frequency': 2978,
  'salience': 21565.245,
  'phrase': 'isikust aktsionär',
  'sentence': 'Üldkoosolekul osalevate aktsionäride ja nende esindajate registreerimine algab samas kell 9.00 . registreerimiseks on aktsionäridel vajalik esitada pass ( esindajatel lisaks sellele võtta kaasa volikiri ) , juriidilisest isikust aktsionäril koopia kehtivast äriregistrikaardist ( esindajal lisaks sellele isikut tõendav dokument ja volikiri ) .'},
 {'lemma': 'isik',
  'frequency': 2978,
  'salience': 21565.245,
  'phrase': 'isikust aktsionär',
  'sentence': 'Juriidilisest isikust aktsionäridel palume esitada registrikaardi'},
 {'lemma': 'isik',
  'frequency': 2978,
  'salience': 21565.245,
  'phrase': 'isikust võlgnik',
  'sentence': '( 4 ) Juriidilisest isikust võlgniku nimel võivad pankrotiavalduse esitada juhatuse või seda asendava organi liikmed ühiselt , täisühingu osanik , usaldusühingu täisosanik , muu seaduses nimetatud isik või organ , samuti likvideerijad ühiselt .'},
 {'lemma': 'isik',
  'frequency': 2978,
  'salience': 21565.245,
  'phrase': 'isikust võlgnik',
  'sentence': '5 ) füüsilisest isikust võlgnik või juriidilisest isikust võlgniku seadusjärgne esindaja teatab võlausaldajale , kohtule või avalikkusele , et ta ei suuda või ei kavatse võlga tasuda või'},
 {'lemma': 'isik',
  'frequency': 2978,
  'salience': 21565.245,
  'phrase': 'isikust võlgnik',
  'sentence': '5 ) füüsilisest isikust võlgnik või juriidilisest isikust võlgniku seadusjärgne esindaja teatab võlausaldajale , kohtule või avalikkusele , et ta ei suuda või ei kavatse võlga tasuda või'},
 {'lemma': 'isik',
  'frequency': 2978,
  'salience': 21565.245,
  'phrase': 'isikust omanik',
  'sentence': '1 ) füüsilisest isikust omaniku puhul nimi ja isikukood ( selle puudumisel sünniaeg ) , juriidilisest isikust omaniku puhul nimi , asukoht , registrikood või registreerimistunnistuse number selle seadusega sätestatud kehtivusaja lõpuni ning avalik-õigusliku juriidilise isiku puhul nimi ;'}]

In [ ]:
with open('../../../../results/reference_corpus_data/elative_construction/elative_attribute_construction.csv', 'w', encoding='utf-8', newline='') as csvfile:
    fieldnames = ['lemma', 'frequency', 'salience', 'phrase', 'sentence']
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(attribute_data)